"""add case_id to approval

Revision ID: 1b7b004b3c68
Revises: 89952e4e5c2d
Create Date: 2026-08-28 06:30:26.538115

Hand-written (not autogenerated as-is): autogenerate against this
deployment's live DB also picked up a large amount of unrelated schema
drift (legacy tables/columns not tracked by the current SQLAlchemy
models, some of which would have been dropped). This migration contains
only the one intended change: a nullable `case_id` column on `approval`,
linking an approval to the case its originating agent session belongs to
(when known).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b7b004b3c68"
down_revision: str | None = "89952e4e5c2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "approval",
        sa.Column("case_id", sa.UUID(), nullable=True),
    )
    op.create_index(
        op.f("ix_approval_case_id"), "approval", ["case_id"], unique=False
    )
    op.create_foreign_key(
        "fk_approval_case_id_case",
        "approval",
        "case",
        ["case_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint("fk_approval_case_id_case", "approval", type_="foreignkey")
    op.drop_index(op.f("ix_approval_case_id"), table_name="approval")
    op.drop_column("approval", "case_id")
