"""add approval case event types

Revision ID: 89952e4e5c2d
Revises: d1535b42ca96
Create Date: 2026-08-25 09:15:48.270856

Hand-authored, not autogenerated as-is: `alembic revision --autogenerate`
against this environment's database also picked up a large amount of
unrelated schema drift (dropped columns/constraints, and several tables —
`soc_cases`, `ioc_history`, `case_sla`, `case_evidence`, `case_tasks`,
`case_metrics`, `ai_decisions`, `workspace_sync_resource_mapping` — that
this deployment added outside Tracecat's own migration history). None of
that belongs in this revision, so only the one change this work actually
needs — three new `caseeventtype` enum values, an additive "expand" change
per `alembic/CLAUDE.md` — is included here.
"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89952e4e5c2d"
down_revision: str | None = "d1535b42ca96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_VALUES = [
    "CASE_CREATED",
    "CASE_UPDATED",
    "CASE_CLOSED",
    "CASE_REOPENED",
    "CASE_VIEWED",
    "PRIORITY_CHANGED",
    "SEVERITY_CHANGED",
    "STATUS_CHANGED",
    "FIELDS_CHANGED",
    "ASSIGNEE_CHANGED",
    "ATTACHMENT_CREATED",
    "ATTACHMENT_DELETED",
    "TAG_ADDED",
    "TAG_REMOVED",
    "PAYLOAD_CHANGED",
    "TASK_CREATED",
    "TASK_DELETED",
    "TASK_STATUS_CHANGED",
    "TASK_PRIORITY_CHANGED",
    "TASK_WORKFLOW_CHANGED",
    "TASK_ASSIGNEE_CHANGED",
    "DROPDOWN_VALUE_CHANGED",
    "TABLE_ROW_LINKED",
    "TABLE_ROW_UNLINKED",
    "COMMENT_CREATED",
    "COMMENT_UPDATED",
    "COMMENT_DELETED",
    "COMMENT_REPLY_CREATED",
    "COMMENT_REPLY_UPDATED",
    "COMMENT_REPLY_DELETED",
]
_NEW_VALUES = [
    "APPROVAL_REQUESTED",
    "APPROVAL_RESOLVED",
    "APPROVAL_TIMED_OUT",
]
_AFFECTED_COLUMNS = [
    TableReference(
        table_schema="public",
        table_name="case_duration_definition",
        column_name="end_event_type",
    ),
    TableReference(
        table_schema="public",
        table_name="case_duration_definition",
        column_name="start_event_type",
    ),
    TableReference(table_schema="public", table_name="case_event", column_name="type"),
]


def upgrade() -> None:
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="caseeventtype",
        new_values=_OLD_VALUES + _NEW_VALUES,
        affected_columns=_AFFECTED_COLUMNS,
        enum_values_to_rename=[],
    )


def downgrade() -> None:
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="caseeventtype",
        new_values=_OLD_VALUES,
        affected_columns=_AFFECTED_COLUMNS,
        enum_values_to_rename=[],
    )
